menu:
#- {name: 'publications', url: '/publications'}
#- {name: 'cv', url: 'https://drive.google.com/file/d/1SkWtu1H9wKOFWpnm7WIzMehkJOJuX_-T/view'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/kdh-yu'}
- {icon: 'x-twitter', link: 'https://x.com/kdhyuu'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/kimdohoon/'}

contacts:
- {name: 'Dohoon Kim', title: 'M.S. & Ph.D Course', department: 'Graduate School of Data Science', institution: 'Seoul National University', institution_address: '1 Gwanak-ro, Gwanak-gu, Seoul', phone: '(000) 000-0000', email: 'dohoon@snu.ac.kr', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
